# coding: utf-8

"""
    Cohesity REST API

    This API provides operations for interfacing with the Cohesity Cluster. NOTE: To view the documentation on the responses, click 'Model' next to 'Example Value' and keep clicking to expand the hierarchy.

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

from pprint import pformat
from six import iteritems
import re


class CloneDirectoryParams(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, destination_directory_name=None, destination_parent_directory_path=None, source_directory_path=None):
        """
        CloneDirectoryParams - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'destination_directory_name': 'str',
            'destination_parent_directory_path': 'str',
            'source_directory_path': 'str'
        }

        self.attribute_map = {
            'destination_directory_name': 'destinationDirectoryName',
            'destination_parent_directory_path': 'destinationParentDirectoryPath',
            'source_directory_path': 'sourceDirectoryPath'
        }

        self._destination_directory_name = destination_directory_name
        self._destination_parent_directory_path = destination_parent_directory_path
        self._source_directory_path = source_directory_path

    @property
    def destination_directory_name(self):
        """
        Gets the destination_directory_name of this CloneDirectoryParams.
        Name of the new directory which will contain the clone contents.

        :return: The destination_directory_name of this CloneDirectoryParams.
        :rtype: str
        """
        return self._destination_directory_name

    @destination_directory_name.setter
    def destination_directory_name(self, destination_directory_name):
        """
        Sets the destination_directory_name of this CloneDirectoryParams.
        Name of the new directory which will contain the clone contents.

        :param destination_directory_name: The destination_directory_name of this CloneDirectoryParams.
        :type: str
        """

        self._destination_directory_name = destination_directory_name

    @property
    def destination_parent_directory_path(self):
        """
        Gets the destination_parent_directory_path of this CloneDirectoryParams.
        Specifies the path of the destination parent directory. The source dir would be cloned as a child of dest parent dir.

        :return: The destination_parent_directory_path of this CloneDirectoryParams.
        :rtype: str
        """
        return self._destination_parent_directory_path

    @destination_parent_directory_path.setter
    def destination_parent_directory_path(self, destination_parent_directory_path):
        """
        Sets the destination_parent_directory_path of this CloneDirectoryParams.
        Specifies the path of the destination parent directory. The source dir would be cloned as a child of dest parent dir.

        :param destination_parent_directory_path: The destination_parent_directory_path of this CloneDirectoryParams.
        :type: str
        """

        self._destination_parent_directory_path = destination_parent_directory_path

    @property
    def source_directory_path(self):
        """
        Gets the source_directory_path of this CloneDirectoryParams.
        Specifies the path of the source directory

        :return: The source_directory_path of this CloneDirectoryParams.
        :rtype: str
        """
        return self._source_directory_path

    @source_directory_path.setter
    def source_directory_path(self, source_directory_path):
        """
        Sets the source_directory_path of this CloneDirectoryParams.
        Specifies the path of the source directory

        :param source_directory_path: The source_directory_path of this CloneDirectoryParams.
        :type: str
        """

        self._source_directory_path = source_directory_path

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
