# coding: utf-8

"""
    Cohesity REST API

    This API provides operations for interfacing with the Cohesity Cluster. NOTE: To view the documentation on the responses, click 'Model' next to 'Example Value' and keep clicking to expand the hierarchy.

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

from pprint import pformat
from six import iteritems
import re


class FilePathFilter(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, exclude_filters=None, protect_filters=None):
        """
        FilePathFilter - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'exclude_filters': 'list[str]',
            'protect_filters': 'list[str]'
        }

        self.attribute_map = {
            'exclude_filters': 'excludeFilters',
            'protect_filters': 'protectFilters'
        }

        self._exclude_filters = exclude_filters
        self._protect_filters = protect_filters

    @property
    def exclude_filters(self):
        """
        Gets the exclude_filters of this FilePathFilter.
        Specifies filters to match files or directories that should be removed from the list of objects matching ProtectFilters.

        :return: The exclude_filters of this FilePathFilter.
        :rtype: list[str]
        """
        return self._exclude_filters

    @exclude_filters.setter
    def exclude_filters(self, exclude_filters):
        """
        Sets the exclude_filters of this FilePathFilter.
        Specifies filters to match files or directories that should be removed from the list of objects matching ProtectFilters.

        :param exclude_filters: The exclude_filters of this FilePathFilter.
        :type: list[str]
        """

        self._exclude_filters = exclude_filters

    @property
    def protect_filters(self):
        """
        Gets the protect_filters of this FilePathFilter.
        Specifies filters to match files or directories that should be protected.

        :return: The protect_filters of this FilePathFilter.
        :rtype: list[str]
        """
        return self._protect_filters

    @protect_filters.setter
    def protect_filters(self, protect_filters):
        """
        Sets the protect_filters of this FilePathFilter.
        Specifies filters to match files or directories that should be protected.

        :param protect_filters: The protect_filters of this FilePathFilter.
        :type: list[str]
        """

        self._protect_filters = protect_filters

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
