# coding: utf-8

"""
    Cohesity REST API

    This API provides operations for interfacing with the Cohesity Cluster. NOTE: To view the documentation on the responses, click 'Model' next to 'Example Value' and keep clicking to expand the hierarchy.

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

from pprint import pformat
from six import iteritems
import re


class IscsiSanPort(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, ip_address=None, iqn=None, tcp_port=None):
        """
        IscsiSanPort - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'ip_address': 'str',
            'iqn': 'str',
            'tcp_port': 'int'
        }

        self.attribute_map = {
            'ip_address': 'ipAddress',
            'iqn': 'iqn',
            'tcp_port': 'tcpPort'
        }

        self._ip_address = ip_address
        self._iqn = iqn
        self._tcp_port = tcp_port

    @property
    def ip_address(self):
        """
        Gets the ip_address of this IscsiSanPort.
        Specifies the IP address of the SAN port.

        :return: The ip_address of this IscsiSanPort.
        :rtype: str
        """
        return self._ip_address

    @ip_address.setter
    def ip_address(self, ip_address):
        """
        Sets the ip_address of this IscsiSanPort.
        Specifies the IP address of the SAN port.

        :param ip_address: The ip_address of this IscsiSanPort.
        :type: str
        """

        self._ip_address = ip_address

    @property
    def iqn(self):
        """
        Gets the iqn of this IscsiSanPort.
        Specifies the qualified name of the iSCSI port (IQN).

        :return: The iqn of this IscsiSanPort.
        :rtype: str
        """
        return self._iqn

    @iqn.setter
    def iqn(self, iqn):
        """
        Sets the iqn of this IscsiSanPort.
        Specifies the qualified name of the iSCSI port (IQN).

        :param iqn: The iqn of this IscsiSanPort.
        :type: str
        """

        self._iqn = iqn

    @property
    def tcp_port(self):
        """
        Gets the tcp_port of this IscsiSanPort.
        Specifies the listening port(tcp) of the SAN port.

        :return: The tcp_port of this IscsiSanPort.
        :rtype: int
        """
        return self._tcp_port

    @tcp_port.setter
    def tcp_port(self, tcp_port):
        """
        Sets the tcp_port of this IscsiSanPort.
        Specifies the listening port(tcp) of the SAN port.

        :param tcp_port: The tcp_port of this IscsiSanPort.
        :type: int
        """

        self._tcp_port = tcp_port

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
