# coding: utf-8

"""
    Cohesity REST API

    This API provides operations for interfacing with the Cohesity Cluster. NOTE: To view the documentation on the responses, click 'Model' next to 'Example Value' and keep clicking to expand the hierarchy.

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

from pprint import pformat
from six import iteritems
import re


class MountVolumesState(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, bring_disks_online=None, mount_volume_results=None, other_error=None, target_source_id=None, username=None):
        """
        MountVolumesState - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'bring_disks_online': 'bool',
            'mount_volume_results': 'list[MountVolumeResult]',
            'other_error': 'MountVolumesStateOtherError',
            'target_source_id': 'int',
            'username': 'str'
        }

        self.attribute_map = {
            'bring_disks_online': 'bringDisksOnline',
            'mount_volume_results': 'mountVolumeResults',
            'other_error': 'otherError',
            'target_source_id': 'targetSourceId',
            'username': 'username'
        }

        self._bring_disks_online = bring_disks_online
        self._mount_volume_results = mount_volume_results
        self._other_error = other_error
        self._target_source_id = target_source_id
        self._username = username

    @property
    def bring_disks_online(self):
        """
        Gets the bring_disks_online of this MountVolumesState.
        Optional setting that determines if the volumes are brought online on the mount target after attaching the disks. This option is only significant for VMs.

        :return: The bring_disks_online of this MountVolumesState.
        :rtype: bool
        """
        return self._bring_disks_online

    @bring_disks_online.setter
    def bring_disks_online(self, bring_disks_online):
        """
        Sets the bring_disks_online of this MountVolumesState.
        Optional setting that determines if the volumes are brought online on the mount target after attaching the disks. This option is only significant for VMs.

        :param bring_disks_online: The bring_disks_online of this MountVolumesState.
        :type: bool
        """

        self._bring_disks_online = bring_disks_online

    @property
    def mount_volume_results(self):
        """
        Gets the mount_volume_results of this MountVolumesState.
        Specifies the results of mounting each specified volume.

        :return: The mount_volume_results of this MountVolumesState.
        :rtype: list[MountVolumeResult]
        """
        return self._mount_volume_results

    @mount_volume_results.setter
    def mount_volume_results(self, mount_volume_results):
        """
        Sets the mount_volume_results of this MountVolumesState.
        Specifies the results of mounting each specified volume.

        :param mount_volume_results: The mount_volume_results of this MountVolumesState.
        :type: list[MountVolumeResult]
        """

        self._mount_volume_results = mount_volume_results

    @property
    def other_error(self):
        """
        Gets the other_error of this MountVolumesState.


        :return: The other_error of this MountVolumesState.
        :rtype: MountVolumesStateOtherError
        """
        return self._other_error

    @other_error.setter
    def other_error(self, other_error):
        """
        Sets the other_error of this MountVolumesState.


        :param other_error: The other_error of this MountVolumesState.
        :type: MountVolumesStateOtherError
        """

        self._other_error = other_error

    @property
    def target_source_id(self):
        """
        Gets the target_source_id of this MountVolumesState.
        Specifies the target Protection Source Id where the volumes will be mounted. NOTE: The source that was backed up and the mount target must be the same type, for example if the source is a VMware VM, then the mount target must also be a VMware VM. The mount target must be registered on the Cohesity Cluster.

        :return: The target_source_id of this MountVolumesState.
        :rtype: int
        """
        return self._target_source_id

    @target_source_id.setter
    def target_source_id(self, target_source_id):
        """
        Sets the target_source_id of this MountVolumesState.
        Specifies the target Protection Source Id where the volumes will be mounted. NOTE: The source that was backed up and the mount target must be the same type, for example if the source is a VMware VM, then the mount target must also be a VMware VM. The mount target must be registered on the Cohesity Cluster.

        :param target_source_id: The target_source_id of this MountVolumesState.
        :type: int
        """

        self._target_source_id = target_source_id

    @property
    def username(self):
        """
        Gets the username of this MountVolumesState.
        Specifies the username to access the mount target.

        :return: The username of this MountVolumesState.
        :rtype: str
        """
        return self._username

    @username.setter
    def username(self, username):
        """
        Sets the username of this MountVolumesState.
        Specifies the username to access the mount target.

        :param username: The username of this MountVolumesState.
        :type: str
        """

        self._username = username

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
