# coding: utf-8

"""
    Cohesity REST API

    This API provides operations for interfacing with the Cohesity Cluster. NOTE: To view the documentation on the responses, click 'Model' next to 'Example Value' and keep clicking to expand the hierarchy.

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

from pprint import pformat
from six import iteritems
import re


class PhysicalEnvJobParameters(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, incremental_snapshot_upon_restart=None):
        """
        PhysicalEnvJobParameters - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'incremental_snapshot_upon_restart': 'bool'
        }

        self.attribute_map = {
            'incremental_snapshot_upon_restart': 'incrementalSnapshotUponRestart'
        }

        self._incremental_snapshot_upon_restart = incremental_snapshot_upon_restart

    @property
    def incremental_snapshot_upon_restart(self):
        """
        Gets the incremental_snapshot_upon_restart of this PhysicalEnvJobParameters.
        If true, performs an incremental backup after server restarts. Otherwise a full backup is done. NOTE: This is applicable only to Windows servers. If not set, default value is false.

        :return: The incremental_snapshot_upon_restart of this PhysicalEnvJobParameters.
        :rtype: bool
        """
        return self._incremental_snapshot_upon_restart

    @incremental_snapshot_upon_restart.setter
    def incremental_snapshot_upon_restart(self, incremental_snapshot_upon_restart):
        """
        Sets the incremental_snapshot_upon_restart of this PhysicalEnvJobParameters.
        If true, performs an incremental backup after server restarts. Otherwise a full backup is done. NOTE: This is applicable only to Windows servers. If not set, default value is false.

        :param incremental_snapshot_upon_restart: The incremental_snapshot_upon_restart of this PhysicalEnvJobParameters.
        :type: bool
        """

        self._incremental_snapshot_upon_restart = incremental_snapshot_upon_restart

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
