# coding: utf-8

"""
    Cohesity REST API

    This API provides operations for interfacing with the Cohesity Cluster. NOTE: To view the documentation on the responses, click 'Model' next to 'Example Value' and keep clicking to expand the hierarchy.

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

from __future__ import absolute_import

import os
import sys
import unittest

import cohesity
from cohesity.rest import ApiException
from cohesity.apis.vaults_api import VaultsApi


class TestVaultsApi(unittest.TestCase):
    """ VaultsApi unit test stubs """

    def setUp(self):
        self.api = cohesity.apis.vaults_api.VaultsApi()

    def tearDown(self):
        pass

    def test_create_vault(self):
        """
        Test case for create_vault

        Create a new Vault (External Target).
        """
        pass

    def test_delete_vault(self):
        """
        Test case for delete_vault

        Delete a Vault (External Target).
        """
        pass

    def test_get_archive_media_info(self):
        """
        Test case for get_archive_media_info

        List the media information for the specified archive service.
        """
        pass

    def test_get_vault_by_id(self):
        """
        Test case for get_vault_by_id

        List details about a single Vault (External Target).
        """
        pass

    def test_get_vault_encryption_key_info(self):
        """
        Test case for get_vault_encryption_key_info

        Get encryption information for a Vault (External Target). A Vault is equivalent to an External Target in the Cohesity Dashboard.
        """
        pass

    def test_get_vaults(self):
        """
        Test case for get_vaults

        List the Vaults (External Targets) registered on the Cohesity Cluster filtered by the specified parameters.
        """
        pass

    def test_update_vault(self):
        """
        Test case for update_vault

        Update a Vault (External Target).
        """
        pass


if __name__ == '__main__':
    unittest.main()
