# coding: utf-8

"""
    Cohesity REST API

    This API provides operations for interfacing with the Cohesity Cluster. NOTE: To view the documentation on the responses, click 'Model' next to 'Example Value' and keep clicking to expand the hierarchy.

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

from __future__ import absolute_import

import os
import sys
import unittest

import cohesity
from cohesity.rest import ApiException
from cohesity.apis.protection_sources_api import ProtectionSourcesApi


class TestProtectionSourcesApi(unittest.TestCase):
    """ ProtectionSourcesApi unit test stubs """

    def setUp(self):
        self.api = cohesity.apis.protection_sources_api.ProtectionSourcesApi()

    def tearDown(self):
        pass

    def test_get_protection_sources_object_by_id(self):
        """
        Test case for get_protection_sources_object_by_id

        Get details about a single Protection Source Object.
        """
        pass

    def test_get_protection_sources_objects(self):
        """
        Test case for get_protection_sources_objects

        List details about Protection Source objects.
        """
        pass

    def test_list_application_servers(self):
        """
        Test case for list_application_servers

        Returns the registered Application Servers and their Object subtrees.
        """
        pass

    def test_list_protected_vms(self):
        """
        Test case for list_protected_vms

        Returns the list of protected VMs in a registered Protection Source tree.
        """
        pass

    def test_list_protection_sources(self):
        """
        Test case for list_protection_sources

        Returns the registered Protection Sources and their Object subtrees.
        """
        pass

    def test_list_protection_sources_registration_info(self):
        """
        Test case for list_protection_sources_registration_info

        
        """
        pass

    def test_list_protection_sources_root_nodes(self):
        """
        Test case for list_protection_sources_root_nodes

        Returns the top level (root) Protection Sources with registration information.
        """
        pass

    def test_list_sql_aag_hosts_and_databases(self):
        """
        Test case for list_sql_aag_hosts_and_databases

        Returns the registered Protection Sources and their Object subtrees.
        """
        pass

    def test_list_virtual_machines(self):
        """
        Test case for list_virtual_machines

        Returns the Virtual Machines in a vCenter Server.
        """
        pass

    def test_refresh_protection_source_by_id(self):
        """
        Test case for refresh_protection_source_by_id

        Refresh the Object hierarchy of the Protection Sources tree.
        """
        pass

    def test_register_application_servers(self):
        """
        Test case for register_application_servers

        Register a Protection Source as running one or more Application Servers like Microsoft SQL servers or Microsoft Exchange servers.
        """
        pass

    def test_register_protection_source(self):
        """
        Test case for register_protection_source

        Register a Protection Source.
        """
        pass

    def test_unregister_application_servers(self):
        """
        Test case for unregister_application_servers

        Unregister Application Servers like Microsoft SQL servers or Microsoft Exchange servers running on a Protection Source.
        """
        pass

    def test_update_application_servers(self):
        """
        Test case for update_application_servers

        Modifies the registration parameters of Application Servers in a Protection Source.
        """
        pass

    def test_upgrade_physical_agents(self):
        """
        Test case for upgrade_physical_agents

        Initiate a request to upgrade Cohesity agents on one or more Physical Servers registered on the Cohesity Cluster.
        """
        pass


if __name__ == '__main__':
    unittest.main()
