# coding: utf-8

"""
    Cohesity REST API

    This API provides operations for interfacing with the Cohesity Cluster. NOTE: To view the documentation on the responses, click 'Model' next to 'Example Value' and keep clicking to expand the hierarchy.

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

from __future__ import absolute_import

import os
import sys
import unittest

import cohesity
from cohesity.rest import ApiException
from cohesity.apis.restore_tasks_api import RestoreTasksApi


class TestRestoreTasksApi(unittest.TestCase):
    """ RestoreTasksApi unit test stubs """

    def setUp(self):
        self.api = cohesity.apis.restore_tasks_api.RestoreTasksApi()

    def tearDown(self):
        pass

    def test_cancel_restore_task(self):
        """
        Test case for cancel_restore_task

        Cancel a recover or clone task with specified id.
        """
        pass

    def test_create_applications_clone_task(self):
        """
        Test case for create_applications_clone_task

        Create a Restore Task for cloning Applications like SQL Databases.
        """
        pass

    def test_create_applications_recover_task(self):
        """
        Test case for create_applications_recover_task

        Create a Restore Task for recovering Applications like SQL Databases.
        """
        pass

    def test_create_clone_task(self):
        """
        Test case for create_clone_task

        Create a Restore Task for cloning VMs or a View.
        """
        pass

    def test_create_recover_task(self):
        """
        Test case for create_recover_task

        Create a Restore Task for recovering VMs or instantly mounting volumes.
        """
        pass

    def test_create_restore_files_task(self):
        """
        Test case for create_restore_files_task

        Create a Restore Task for recovering files and folders.
        """
        pass

    def test_get_file_snapshots_information(self):
        """
        Test case for get_file_snapshots_information

        Get the information about snapshots that contain the specified file or folder. In addition, information about the file or folder is provided.
        """
        pass

    def test_get_restore_task_by_id(self):
        """
        Test case for get_restore_task_by_id

        List details about a single Restore Task.
        """
        pass

    def test_get_restore_tasks(self):
        """
        Test case for get_restore_tasks

        List the Restore Tasks filtered by the specified parameters.
        """
        pass

    def test_get_vm_volumes_information(self):
        """
        Test case for get_vm_volumes_information

        Get information about the logical volumes found in a VM.
        """
        pass

    def test_search_objects(self):
        """
        Test case for search_objects

        Find backup objects that match the specified search and filter criteria on the Cohesity Cluster.
        """
        pass

    def test_search_restored_files(self):
        """
        Test case for search_restored_files

        Search for files and folders to recover that match the specified search and filter criteria on the Cohesity Cluster.
        """
        pass


if __name__ == '__main__':
    unittest.main()
