# coding: utf-8

"""
    Cohesity REST API

    This API provides operations for interfacing with the Cohesity Cluster. NOTE: To view the documentation on the responses, click 'Model' next to 'Example Value' and keep clicking to expand the hierarchy.

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

from __future__ import absolute_import

import os
import sys
import unittest

import cohesity
from cohesity.rest import ApiException
from cohesity.apis.active_directory_api import ActiveDirectoryApi


class TestActiveDirectoryApi(unittest.TestCase):
    """ ActiveDirectoryApi unit test stubs """

    def setUp(self):
        self.api = cohesity.apis.active_directory_api.ActiveDirectoryApi()

    def tearDown(self):
        pass

    def test_add_active_directory_principals(self):
        """
        Test case for add_active_directory_principals

        Add multiple groups or users on the Cohesity Cluster for the specified Active Directory principals. In addition, assign Cohesity roles to the users or groups to define their Cohesity privileges.
        """
        pass

    def test_create_active_directory_entry(self):
        """
        Test case for create_active_directory_entry

        Join the Cohesity Cluster to the specified Active Directory.
        """
        pass

    def test_delete_active_directory_entry(self):
        """
        Test case for delete_active_directory_entry

        Deletes the join with the Active Directory.
        """
        pass

    def test_get_active_directory_entry(self):
        """
        Test case for get_active_directory_entry

        Lists the Active Directories that the Cohesity Cluster has joined.
        """
        pass

    def test_list_centrify_zones(self):
        """
        Test case for list_centrify_zones

        Fetches the list centrify zones of an active directory domain.
        """
        pass

    def test_search_active_directory_principals(self):
        """
        Test case for search_active_directory_principals

        List the user and group principals in the Active Directory that match the filter criteria specified using parameters.
        """
        pass

    def test_update_active_directory_id_mapping(self):
        """
        Test case for update_active_directory_id_mapping

        Updates the user id mapping info of an Active Directory.
        """
        pass

    def test_update_active_directory_machine_accounts(self):
        """
        Test case for update_active_directory_machine_accounts

        Updates the machine accounts of an Active Directory.
        """
        pass


if __name__ == '__main__':
    unittest.main()
